# Generated by Django 4.0.3 on 2022-03-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_patient_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
    ]
